=== nithinaakash/Ncp_master/src/main/webapp/project/Xml/cat1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="title"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="title">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="date"/>
        <xs:element ref="int"/>
        <xs:element ref="name1"/>
        <xs:element ref="name2"/>
        <xs:element ref="name3"/>
      </xs:sequence>
      <xs:attribute name="category" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="date" type="xs:date"/>
  <xs:element name="int">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:pattern value="[0-9]*"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="name1">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="[A-Za-z ]*"/>
        <xs:whiteSpace value="preserve"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="name2" >
  <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="[A-Za-z ]*"/>
        <xs:whiteSpace value="preserve"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="name3" >
  <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="[A-Za-z ]*"/>
        <xs:whiteSpace value="preserve"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
</xs:schema>

=== nithinaakash/Ncp_master/src/main/webapp/project/Xml/cat1.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE root SYSTEM "title.dtd">
<?xml-stylesheet type="text/xsl"  href="cat1.xsl"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cat1.xsd">
    <title category="medicine">
        <date>2002/11/08</date>
        <int>3</int>
        <name1>Dosim etrist</name1>
        <name2>Anesthesiologist</name2>
        <name3>Cardiac Perfusionist</name3>
    </title>
    <title category="Math">
        <date>2002/11/5</date>
        <int>4</int>
        <name1>Actuary</name1>
        <name2> Financial Analyst</name2>
        <name3> Personal Financial Advisory </name3>
    </title>
    <title category="Technology">
        <date>2002/11/6</date>
        <int>7</int>
        <name1>WebDeveloper</name1>
        <name2> Computer Network Architect</name2>
        <name3>Information Security Analyst </name3>
    </title>
    <title category="Computer Network Architect">
        <date>2002/11/9</date>
        <int>6</int>
        <name1>Network</name1>
        <name2>  Architect</name2>
        <name3>Information </name3>
    </title>
    <title category="Finacial Analyst">
        <date>2002/11/7</date>
        <int>43</int>
        <name1>Finance</name1>
        <name2> Computer</name2>
        <name3> Analyst </name3>
    </title>
</root>
